"""Package project code+docs into zip archives (max 10 files each)."""
import os, zipfile, shutil

ROOT = os.path.dirname(os.path.abspath(__file__))
OUT  = os.path.join(ROOT, "zip_release")
shutil.rmtree(OUT, ignore_errors=True)
os.makedirs(OUT)

GROUPS = {
    "01_project_root": [
        "README.md",
        "requirements.txt",
        "pyproject.toml",
        "quant_framework/__init__.py",
        "quant_framework/model/__init__.py",
        "quant_framework/analysis/__init__.py",
        "quant_framework/analysis/performance.py",
        "quant_framework/visualization/__init__.py",
        "quant_framework/visualization/plotter.py",
    ],
    "02_backtest_core": [
        "quant_framework/backtest/__init__.py",
        "quant_framework/backtest/config.py",
        "quant_framework/backtest/kernels.py",
        "quant_framework/backtest/backtest_engine.py",
        "quant_framework/backtest/protocols.py",
        "quant_framework/backtest/fill_simulator.py",
        "quant_framework/backtest/manifest.py",
    ],
    "03_backtest_robust": [
        "quant_framework/backtest/bias_detector.py",
        "quant_framework/backtest/order_manager.py",
        "quant_framework/backtest/portfolio.py",
        "quant_framework/backtest/robust.py",
        "quant_framework/backtest/robust_scan.py",
        "quant_framework/backtest/tca.py",
    ],
    "04_data_core": [
        "quant_framework/data/__init__.py",
        "quant_framework/data/data_manager.py",
        "quant_framework/data/dataset.py",
        "quant_framework/data/indicators.py",
        "quant_framework/data/cache_manager.py",
        "quant_framework/data/rag_context.py",
        "quant_framework/data/adapters/__init__.py",
        "quant_framework/data/adapters/base_adapter.py",
        "quant_framework/data/adapters/file_adapter.py",
        "quant_framework/data/adapters/api_adapter.py",
    ],
    "05_data_storage": [
        "quant_framework/data/adapters/database_adapter.py",
        "quant_framework/data/storage/__init__.py",
        "quant_framework/data/storage/arrow_ipc_storage.py",
        "quant_framework/data/storage/binary_mmap_storage.py",
        "quant_framework/data/storage/parquet_storage.py",
    ],
    "06_strategy": [
        "quant_framework/strategy/__init__.py",
        "quant_framework/strategy/base_strategy.py",
        "quant_framework/strategy/ma_strategy.py",
        "quant_framework/strategy/rsi_strategy.py",
        "quant_framework/strategy/macd_strategy.py",
        "quant_framework/strategy/kama_strategy.py",
        "quant_framework/strategy/mesa_strategy.py",
        "quant_framework/strategy/drift_regime_strategy.py",
        "quant_framework/strategy/lorentzian_strategy.py",
        "quant_framework/strategy/adaptive_regime_ensemble.py",
    ],
    "07_strategy_ext_alpha": [
        "quant_framework/strategy/microstructure_momentum.py",
        "quant_framework/strategy/momentum_breakout_strategy.py",
        "quant_framework/strategy/zscore_reversion_strategy.py",
        "quant_framework/alpha/__init__.py",
        "quant_framework/alpha/cross_asset.py",
        "quant_framework/alpha/evaluator.py",
        "quant_framework/alpha/order_flow.py",
        "quant_framework/alpha/volatility.py",
    ],
    "08_live_trading": [
        "quant_framework/live/__init__.py",
        "quant_framework/live/kernel_adapter.py",
        "quant_framework/live/trading_runner.py",
        "quant_framework/live/price_feed.py",
        "quant_framework/live/risk.py",
        "quant_framework/live/trade_journal.py",
        "quant_framework/live/latency.py",
        "quant_framework/live/replay.py",
    ],
    "09_broker_dashboard": [
        "quant_framework/broker/__init__.py",
        "quant_framework/broker/base.py",
        "quant_framework/broker/paper.py",
        "quant_framework/dashboard/__init__.py",
        "quant_framework/dashboard/app.py",
        "quant_framework/dashboard/charts.py",
    ],
    "10_rag_core": [
        "quant_framework/rag/__init__.py",
        "quant_framework/rag/config.py",
        "quant_framework/rag/core.py",
        "quant_framework/rag/pipeline.py",
        "quant_framework/rag/prompts.py",
        "quant_framework/rag/types.py",
        "quant_framework/rag/README.md",
        "quant_framework/rag/retrieval/__init__.py",
        "quant_framework/rag/retrieval/reranker.py",
        "quant_framework/rag/retrieval/retriever.py",
    ],
    "11_rag_ingestion": [
        "quant_framework/rag/ingestion/__init__.py",
        "quant_framework/rag/ingestion/base.py",
        "quant_framework/rag/ingestion/directory_adapter.py",
        "quant_framework/rag/ingestion/file_watcher.py",
        "quant_framework/rag/ingestion/queue.py",
        "quant_framework/rag/ingestion/stream.py",
    ],
    "12_rag_processing_store": [
        "quant_framework/rag/processing/__init__.py",
        "quant_framework/rag/processing/chunker.py",
        "quant_framework/rag/processing/embedder.py",
        "quant_framework/rag/processing/normalizer.py",
        "quant_framework/rag/processing/pipeline.py",
        "quant_framework/rag/store/__init__.py",
        "quant_framework/rag/store/keyword_index.py",
        "quant_framework/rag/store/vector_store.py",
    ],
    "13_tests": [
        "tests/__init__.py",
        "tests/conftest.py",
        "tests/test_backtest.py",
        "tests/test_broker.py",
        "tests/test_indicators.py",
        "tests/test_kernel_regression.py",
        "tests/test_live.py",
        "tests/test_new_modules.py",
        "tests/test_performance.py",
        "tests/test_replay.py",
    ],
    "14_tests_ext": [
        "tests/test_elite_strategies.py",
        "tests/test_lorentzian_optimization.py",
        "tests/test_rag_backtest.py",
        "tests/test_rag_full_chain.py",
        "tests/test_rag_realtime_stress.py",
        "tests/test_strategies.py",
    ],
    "15_examples_backtest": [
        "examples/demo_backtest_api.py",
        "examples/example_ma_strategy.py",
        "examples/unified_backtest.py",
        "examples/param_scan_benchmark.py",
        "examples/benchmark_backtest_performance.py",
        "examples/example_robust_backtest.py",
        "examples/robust_backtest_api.py",
        "examples/run_real_market_backtest.py",
        "examples/realistic_full_scan.py",
        "examples/full_strategy_analysis.py",
    ],
    "16_examples_advanced": [
        "examples/advanced_strategies_benchmark.py",
        "examples/cutting_edge_strategies.py",
        "examples/crypto_full_benchmark.py",
        "examples/comprehensive_robust_scan.py",
        "examples/walk_forward_robust_scan.py",
        "examples/long_short_leveraged_scan.py",
        "examples/next_open_full_scan.py",
        "examples/optimize_all_strategies_next_open.py",
        "examples/param_decay_study.py",
        "examples/investment_research.py",
    ],
    "17_examples_multi_tf_live": [
        "examples/multi_tf_backtest_example.py",
        "examples/comprehensive_multi_tf_analysis.py",
        "examples/benchmark_multi_tf.py",
        "examples/multi_timeframe_analysis.py",
        "examples/intraday_analysis.py",
        "examples/leverage_analysis.py",
        "examples/download_5m_data.py",
        "examples/download_multi_tf_data.py",
        "examples/paper_trading.py",
        "examples/technical_benchmark.py",
    ],
    "18_examples_rag_misc": [
        "examples/example_rag.py",
        "examples/example_rag_with_backtest.py",
        "examples/example_execution_diagnostics.py",
        "examples/realtime_signal_analysis.py",
        "examples/dashboard_preview.py",
    ],
    "19_docs_guides": [
        "docs/INDEX.md",
        "docs/ARCHITECTURE.md",
        "docs/DESIGN.md",
        "docs/BEGINNER_GUIDE.md",
        "docs/PROJECT_KNOWLEDGE.md",
        "docs/UPGRADE_PLAN_V1.md",
        "docs/STRATEGY_ARSENAL.md",
        "docs/OPTIMIZATION.md",
        "docs/IO_FAST.md",
        "docs/PERFORMANCE.md",
    ],
    "20_docs_comparison": [
        "docs/COMPARISON.md",
        "docs/FRAMEWORK_COMPARISON.md",
        "docs/QUANT_FRAMEWORK_COMPARISON.md",
        "docs/INSTITUTIONAL_QUANT_VS_FRAMEWORK.md",
        "docs/BACKTEST_VS_LIVE.md",
        "docs/EXECUTION_DIAGNOSTICS.md",
        "docs/LIVE_TRADING_AND_LATENCY.md",
        "docs/FREQUENCY_SUPPORT.md",
        "docs/FREQTRADE_BACKTEST_LIVE_ANALYSIS.md",
        "docs/ROBUST_BACKTEST.md",
    ],
    "21_docs_reports": [
        "docs/COMPREHENSIVE_BACKTEST_ANALYSIS_V3.md",
        "docs/COMPREHENSIVE_ROBUST_REPORT.md",
        "docs/CRYPTO_BENCHMARK_REPORT.md",
        "docs/LONG_SHORT_LEVERAGED_REPORT.md",
        "docs/ROBUST_ANTI_OVERFIT_REPORT.md",
        "docs/NEXT_OPEN_FULL_SCAN_REPORT.md",
        "docs/ALL_STRATEGIES_NEXT_OPEN_REPORT.md",
        "docs/INVESTMENT_RESEARCH_REPORT.md",
        "docs/PARAM_DECAY_STUDY.md",
        "docs/VALIDATION_REPORT.md",
    ],
    "22_docs_misc_reports": [
        "docs/AUDIT.md",
        "docs/RAG.md",
        "docs/RAG_TEST_REPORT.md",
        "docs/coding_guide.md",
        "docs/POLARS_VS_PANDAS.md",
        "reports/multi_tf_fusion_analysis_v2.md",
        "reports/full_analysis_report.md",
        "reports/technical_benchmark_report.md",
        "reports/multi_timeframe_analysis_report.md",
        "reports/intraday_5m_analysis_report.md",
    ],
}

manifest_lines = [
    "# Quant Framework — ZIP 打包清单",
    "",
    "每个 ZIP 保持原始目录结构，解压到同一目录即可还原完整项目。",
    "",
    "## 还原步骤",
    "",
    "```bash",
    "mkdir quant_project && cd quant_project",
    "for z in *.zip; do unzip -o \"$z\"; done",
    "pip install -r requirements.txt",
    "python -m pytest tests/ -v  # 验证",
    "```",
    "",
    "## ZIP 清单",
    "",
    "| ZIP | 内容 | 文件数 |",
    "|-----|------|--------|",
]

total = 0
for name, files in GROUPS.items():
    assert len(files) <= 10, f"{name} has {len(files)} files (max 10)"
    zpath = os.path.join(OUT, f"{name}.zip")
    with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED) as zf:
        for rel in files:
            full = os.path.join(ROOT, rel)
            if not os.path.isfile(full):
                print(f"  SKIP (not found): {rel}")
                continue
            zf.write(full, rel)
    desc = name.split("_", 1)[1].replace("_", " ")
    manifest_lines.append(f"| `{name}.zip` | {desc} | {len(files)} |")
    total += len(files)
    print(f"  {name}.zip  ({len(files)} files)")

manifest_lines.extend([
    "",
    f"**总计**: {len(GROUPS)} 个 ZIP, {total} 个文件",
    "",
    "## 目录结构概览",
    "",
    "```",
    "Project_1/",
    "├── README.md / requirements.txt / pyproject.toml",
    "├── quant_framework/",
    "│   ├── __init__.py              # 框架入口",
    "│   ├── backtest/                # 回测引擎 (ZIP 02-03)",
    "│   │   ├── kernels.py           # 18 策略 Numba 内核",
    "│   │   ├── config.py            # 回测配置",
    "│   │   ├── robust_scan.py       # 10 层抗过拟合",
    "│   │   └── ...",
    "│   ├── data/                    # 数据层 (ZIP 04-05)",
    "│   │   ├── data_manager.py      # 数据管理器",
    "│   │   ├── adapters/            # 数据源适配器",
    "│   │   └── storage/             # 多层存储",
    "│   ├── strategy/                # 策略层 (ZIP 06-07)",
    "│   │   ├── base_strategy.py     # 策略基类",
    "│   │   └── ...                  # 13 个具体策略",
    "│   ├── alpha/                   # Alpha 因子 (ZIP 07)",
    "│   ├── live/                    # 实盘交易 (ZIP 08)",
    "│   │   ├── kernel_adapter.py    # 内核信号适配",
    "│   │   ├── trading_runner.py    # 交易运行器",
    "│   │   └── risk.py              # 风控",
    "│   ├── broker/                  # 经纪商 (ZIP 09)",
    "│   ├── dashboard/               # 仪表盘 (ZIP 09)",
    "│   ├── rag/                     # RAG 管道 (ZIP 10-12)",
    "│   ├── model/                   # ML 模型 (ZIP 01)",
    "│   ├── analysis/                # 绩效分析 (ZIP 01)",
    "│   └── visualization/           # 可视化 (ZIP 01)",
    "├── examples/                    # 示例脚本 (ZIP 15-18)",
    "├── tests/                       # 测试 (ZIP 13-14)",
    "├── docs/                        # 文档 (ZIP 19-22)",
    "└── reports/                     # 分析报告 (ZIP 22)",
    "```",
])

mpath = os.path.join(OUT, "MANIFEST.md")
with open(mpath, "w") as f:
    f.write("\n".join(manifest_lines) + "\n")
print(f"\nManifest: {mpath}")
print(f"Total: {len(GROUPS)} ZIPs, {total} files")
